name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .npmrc
        run: echo "${{ secrets.NPM_AUTH_TOKEN }}" | base64 --decode > .npmrc
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@networkninja'
      - name: Change to packages/lib directory
        working-directory: packages/lib
        run: |
          npm install
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
